default: &default
  primary:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  tijuana:
    adapter: mysql
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    url: <%= ENV["TIJUANA_DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: db/tijuana_migrate

development:
  <<: *default
test:
  <<: *default
